name: Verilator Regression Test
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
      - uses: actions/checkout@v3
      
      - name: install sdl dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
    
      - name: regression
        run: docker run -v ${{ github.workspace }}:/src -w /src/verilator_sim  --entrypoint make verilator/verilator:stable
          
      - name: Publish Coverage
        run: |
          cd verilator_sim/logs
          bash <(curl -s https://codecov.io/bash) -f coverage.dat -f merged.info
